spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/ssafy
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update